### ISSUE TITLE
Cannot find source code

### ISSUE THREAD

**Issue by tutnes** [dynaTrace/Dynatrace-JSON-Reporting-Plugin#1]
Hi, I am not sure if this is as intended or not. But I cannot seem to find the latest source code for this.

**Comment by centic9** [comment]
Hi, currently the source is not published here, we are discussing how we can best provide it, so please stay tuned :)

**Comment by centic9** [comment]
We are Done! The source-code is now uploaded to the GitHub project so you can do a normal git clone or use the provided source-package of the latest release 5.5.0.1107.
