### ISSUE TITLE
Does not work in 6.5

### ISSUE THREAD

**Issue by josecolella** [dynaTrace/Dynatrace-JSON-Reporting-Plugin#2]
I installed the plugin at a customer today for Dynatrace Application Monitoring 6.5, but the json format does not work. Is this plugin compatible with 6.5?

**Comment by heydenb** [comment]
Same here. I have added the plugin (build from source) but the JSON File Type does not appear. Not in the client and not via the web interface.

**Comment by josecolella** [comment]
I also wanted to mention, that the plugin cannot be deleted after installed. I had to navigate to the plugin directory to delete it.

**Comment by centic9** [comment]
I just tried it with a new installation of Dynatrace 6.5, after installing the plugin I had to restart both server and client (it did tell me via a popup/dialog), then the JSON-option was available. However when actually starting a report, I get:

`2017-01-21 10:05:55 WARNING [Client] An internal system error occurred.: com.dynatrace.diagnostics.report.json.JSONReportRenderer.reportDashboard(Lcom/dynatrace/diagnostics/sdk/dashboard/DashboardInterface;Lcom/dynatrace/diagnostics/sdk/dashboard/DashboardConfig;Ljava/lang/String;Ljava/io/File;Lcom/dynatrace/diagnostics/sdk/dashboard/reporting/ReportType;Ljava/util/Collection;)V`

which indicates that some internals of reporting were changed in an incompatible way, I'll need to take a closer look...

**Comment by centic9** [comment]
I have updated the plugin now to work against 6.5, see https://github.com/Dynatrace/Dynatrace-JSON-Reporting-Plugin/releases, older versions should still work, but I didn't verify it.

**Comment by centic9** [comment]
Regarding the need to uninstall the plugin manually: The plugin needs to be a "system plugin" to properly plug into the reporting system and such plugin-types unfortunately cannot be uninstalled via the UI.
